export const STATUS_ITEM = {
    DISPONIVEL: 'DISPONIVEL',
    MANUTENCAO: 'MANUTENCAO',
    EMPRESTADO: 'EMPRESTADO'
};

export const STATUS_EMPRESTIMO = {
    ATIVO: 'ATIVO',
    CONCLUIDO: 'CONCLUIDO'
};